<?php

namespace Complements\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UbigeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomRepository extends EntityRepository
{
	function create_unique_slug($string, $entity, $parent_id, $separator='-') 
	{ 
		$slug = $this->fixForUri($string, $separator); 
		$similar = $this->similar_slug($entity, $slug);
		
		if(count($similar) > 0) $slug = $slug.$separator.$parent_id;
	   
		return $slug; 
	}

	function similar_slug($entity, $slug) 
	{ 
		$q = $this->_em->createQueryBuilder()->select('e')->from($entity, 'e');
	    $q = $q->where('e.slug = :slug');
	    $q = $q->setParameter('slug', $slug);
	    
		return $q->getQuery()->getResult(); 
	}

	public static function fixForUri($string, $separator){
		$slug = trim($string); // trim the string
		$slug= preg_replace('/[^a-zA-Z0-9 -]/','',$slug ); // only take alphanumerical characters, but keep the spaces and dashes too...
		$slug= str_replace(' ',$separator, $slug); // replace spaces by dashes
		$slug= strtolower($slug);  // make it lowercase
		return $slug;
	}

}
