<?php

namespace Complements\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UbigeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoreInfoRepository extends EntityRepository
{
	
}
