<?php

namespace Complements\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UbigeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbigeoRepository extends EntityRepository
{
	public function getUbigeo($parent_id = null){
	    
	    if(is_null($parent_id)){ //Todas las Provincias 
	    	$q = $this->_em->createQueryBuilder()->select('u')->from('Complements\Entity\Ubigeo', 'u')->where('u.parentId IS NULL');
	    }else{ //Todos los distritos por una provincia
	    	$q = $this->_em->createQueryBuilder()->select('u')->from('Complements\Entity\Ubigeo', 'u')->where('u.parentId = :parentId')->setParameter('parentId', $parent_id);
	    }
	    
	    return $q->getQuery()->getResult();
	}
}
