<?php

namespace Institutions\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TempInstitutionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempInstitutionsRepository extends EntityRepository
{
	
}
